name: Update contributors
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  add-contributors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Delete old contributors-update branch
      uses: dawidd6/action-delete-branch@v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        branches: contributors-update
    - name: Create contributors-update branch
      uses: peterjgrainger/action-create-branch@v2.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: 'contributors-update'
    - name: Auto-add contributors
      uses: BobAnkh/add-contributors@v0.2.2
      with:
        BRANCH: 'contributors-update'
        PULL_REQUEST: 'master'
        CONTRIBUTOR: '## Contributors'
        COLUMN_PER_ROW: '6'
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        IMG_WIDTH: '100'
        FONT_SIZE: '14'
        PATH: '/CONTRIBUTORS.md'
        COMMIT_MESSAGE: 'docs(CONTRIBUTORS): update contributors'
        AVATAR_SHAPE: 'round'
